### ISSUE TITLE
syntax highlighting of float literals in scientific notation

### ISSUE THREAD

**Issue by uvtc** [artursartamonovs/hare-highlight#6]
These float literals aren't being correctly syntax-highlighted:

~~~
1.23e2
1.23e02
1.23e-2
1.23e+2
1.23e-02
1.23e+02
1.23E02
~~~

Although harec doesn't currently (as of this moment) support the capital "E", I got a reply about it on IRC and I think a patch is forthcoming.

**Comment by artursartamonovs** [comment]
Hi, what would be correct to highlight? There is added match that finds and sets color for highlighting floats with small and big letter E


    # float
    - match: '\b(\+|-)?[0-9]+\.[0-9]+((e|E)?(\+|-)?[0-9]+)(f32|f64)?'
      scope: constant.numeric.hare
    # float second
    - match: '\b(\+|-)?[0-9]((e|E)(\+|-)?[0-9]+)?(f32|f64)?\b'
      scope: constant.numeric.hare

**Comment by uvtc** [comment]
Hi. I'd expect all parts of the numeric literal (including "e", "E", any plus or minus signs, and suffixes) to all be rendered the same color.

How could I test that snippet you posted here?

**Comment by artursartamonovs** [comment]
What the version of sublime do you use? All of those are highlighted as you described when I run Sublime. Can you add screenshot?

**Comment by uvtc** [comment]
![sublime-number-literals-and-version](https://github.com/artursartamonovs/hare-highlight/assets/212308/7080a549-9ec4-4da2-93a4-3a050532d7a8)

**Comment by artursartamonovs** [comment]
Thanks, for screenshot I cant reproduce this issue. I will try to find what may cause that.

**Comment by artursartamonovs** [comment]
Found it need to add new tag and update package repository

**Comment by artursartamonovs** [comment]
Seems fixed

**Comment by uvtc** [comment]
Thanks! I opened Sublime, went to "Preferences --> Package Control", and chose "Upgrade Package". It worked for a moment, then the display updated (with number literals now syntax highlighted correctly), and a pop-up dialog said there are no packages ready for upgrade.

So, looks good now!
